### ISSUE TITLE
Also run `grunt docs`

### ISSUE THREAD

**Issue by hnrch02** [twbs/gruntworker#3]
Or a subset of tasks of `grunt docs`

**Comment by cvrebert** [comment]
I propose `grunt clean:docs copy:docs` as the subset

**Comment by hnrch02** [comment]
:+1:

**Comment by XhmikosR** [comment]
IIRC `clean` already runs though.

**Comment by cvrebert** [comment]
`dist` only includes `clean:dist`, not `clean:docs`, as a subtask

**Comment by XhmikosR** [comment]
Yeah, but `docs` includes `clean:docs`.

**Comment by XhmikosR** [comment]
So, doing `grunt dist docs` should be enough.

**Comment by cvrebert** [comment]
`docs` also does lint checks, generates raw-files, and other overkill stuff, hence I am inclined to avoid it.

**Comment by XhmikosR** [comment]
Well, I agree about the lint stuff, but raw-files is still part of docs.

**Comment by cvrebert** [comment]
Yes, but it would cause so much extra churn.
